## **`PANDAS`**

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

2.2.2

# series :-A Series is like a single column in Excel or a list with labels (indexes).

In [ ]:
s=pd.Series([1,2,3,4,5])

In [ ]:
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
ser=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(ser)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
student={
    "name":"vamsi",
    "branch":"aiml"
    }
ser=pd.Series(student)
print(ser)

name      vamsi
branch     aiml
dtype: object

In [ ]:
n=pd.Series([10,20,30,40,50])

In [ ]:
n+2

0    12
1    22
2    32
3    42
4    52
dtype: int64

In [ ]:
n/2

0     5.0
1    10.0
2    15.0
3    20.0
4    25.0
dtype: float64

In [ ]:
s.mean()

np.float64(3.0)

In [ ]:
s.max()

5

In [ ]:
s.sum()

np.int64(15)

In [ ]:
s.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [ ]:
n[n>20]

2    30
3    40
4    50
dtype: int64

In [ ]:
names=pd.Series(['bunny','Rohith','YUNUS'])

In [ ]:
names.str.lower()

0     bunny
1    rohith
2     yunus
dtype: object

In [ ]:
names.str.len()

0    5
1    6
2    5
dtype: int64

In [ ]:
names.str.startswith('Y')

0    False
1    False
2     True
dtype: bool

In [ ]:
student={
    "names":["bunny","rohith","gani"],
    "branch":["aiml","aiml","aiml"]
}
std=[
    {"name":"bunny","branch":"aiml","age":20,},
    {"name":"rohith","branch":"aiml"},
    {"name":"gani","branch":"aiml"}
]
s=pd.DataFrame(std)
print(s)

     name branch   age
0   bunny   aiml  20.0
1  rohith   aiml   NaN
2    gani   aiml   NaN

In [ ]:
import numpy as np

In [ ]:
arr= np.random.rand(3,4)
c=pd.DataFrame(arr,columns=['a','b','c','d'])
print(c)

          a         b         c         d
0  0.052137  0.472816  0.877338  0.310862
1  0.079303  0.876703  0.064018  0.558824
2  0.089795  0.526402  0.544584  0.645468

In [ ]:
data={
    "names":["bunny","rohith","gani","sallu","bharath"],
    "age":[20,21,22,44,43,],
    "score": [60,71,92,78,88],
    "branch":["aiml","aiml","aiml","cse","ece"]
}
df= pd.DataFrame(data)
print(df)

     names  age  score branch
0    bunny   20     60   aiml
1   rohith   21     71   aiml
2     gani   22     92   aiml
3    sallu   44     78    cse
4  bharath   43     88    ece

In [ ]:
df.tail()

     names  age  score branch
0    bunny   20     60   aiml
1   rohith   21     71   aiml
2     gani   22     92   aiml
3    sallu   44     78    cse
4  bharath   43     88    ece

In [ ]:
df.head()

     names  age  score branch
0    bunny   20     60   aiml
1   rohith   21     71   aiml
2     gani   22     92   aiml
3    sallu   44     78    cse
4  bharath   43     88    ece

In [ ]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.dtypes

names     object
age        int64
score      int64
branch    object
dtype: object

In [ ]:
df.nunique()

names     5
age       5
score     5
branch    3
dtype: int64

In [ ]:
df.isnull().sum()

names     0
age       0
score     0
branch    0
dtype: int64

In [ ]:
df['names']
df.names

0      bunny
1     rohith
2       gani
3      sallu
4    bharath
Name: names, dtype: object

In [ ]:
df[['names','age']]

     names  age
0    bunny   20
1   rohith   21
2     gani   22
3    sallu   44
4  bharath   43

In [ ]:
df.loc[0]

names     bunny
age          20
score        60
branch     aiml
Name: 0, dtype: object

In [ ]:
df.loc[0:3,"names":"score"]

    names  age  score
0   bunny   20     60
1  rohith   21     71
2    gani   22     92
3   sallu   44     78

In [ ]:
df.iloc[-1]

names     bharath
age            43
score          88
branch        ece
Name: 4, dtype: object

In [ ]:
df.loc[0,'names']

'bunny'

In [ ]:
df.iloc[0,0]

'bunny'

# filtering rows and columns

In [ ]:
df[df['score']>80]

     names  age  score branch
2     gani   22     92   aiml
4  bharath   43     88    ece

In [ ]:
df[(df['score']>80) & (df['branch']=='aiml')]
df[(df['age']<24) & (df['score']>90)]

  names  age  score branch
2  gani   22     92   aiml

In [ ]:
df.query('score>80 and age < 25')
df.query('branch == "A"')

Empty DataFrame
Columns: [names, age, score, branch]
Index: []

In [ ]:
df[df['names'].isin(['bunny','gani'])]

   names  age  score branch
0  bunny   20     60   aiml
2   gani   22     92   aiml

In [ ]:
df['Example']=["a","b","c","d","e"]

In [ ]:
print(df)

     names  age  score branch Example
0    bunny   20     60   aiml       a
1   rohith   21     71   aiml       b
2     gani   22     92   aiml       c
3    sallu   44     78    cse       d
4  bharath   43     88    ece       e

In [ ]:
df['branch']=df['score']>=80
print(df)

     names  age  score  branch Example
0    bunny   20     60   False       a
1   rohith   21     71   False       b
2     gani   22     92    True       c
3    sallu   44     78   False       d
4  bharath   43     88    True       e

In [ ]:
df['score']=df['score']+5
print(df)

     names  age  score  branch Example
0    bunny   20     65   False       a
1   rohith   21     76   False       b
2     gani   22     97    True       c
3    sallu   44     83   False       d
4  bharath   43     93    True       e

In [ ]:
def percentage():
 if('score'>90):
  return'90%'
 elif("score">60 and "score"<80):
  return'70%'
 else:
  return "fail"
  print(percentage(100))

In [ ]:
def grade(score):
  if score>=90:
    return "A"
  elif score>=80:
    return "B"
  elif score>=70:
    return "C"
  elif score>=60:
    return "D"
  else:
    return "F"
df['branch_letter']=df['score'].apply(grade)
print(df)

     names  age  score  branch Example branch_letter
0    bunny   20     65   False       a             D
1   rohith   21     76   False       b             C
2     gani   22     97    True       c             A
3    sallu   44     83   False       d             B
4  bharath   43     93    True       e             A

In [ ]:
pass_status={
    True:"pass",
    False:"fail"
}
df['result']=df['branch'].map(pass_status)
print(df)

     names  age  score  branch Example branch_letter result
0    bunny   20     65   False       a             D   fail
1   rohith   21     76   False       b             C   fail
2     gani   22     97    True       c             A   pass
3    sallu   44     83   False       d             B   fail
4  bharath   43     93    True       e             A   pass

In [ ]:
result={
    True:"pass",
    False:"fail"
}
df['result']=df['branch'].map(result)
print(df)

     names  age  score  branch Example branch_letter result
0    bunny   20     65   False       a             D   fail
1   rohith   21     76   False       b             C   fail
2     gani   22     97    True       c             A   pass
3    sallu   44     83   False       d             B   fail
4  bharath   43     93    True       e             A   pass

In [ ]:
df.drop("branch_letter",axis=1,inplace=True)

In [ ]:
print(df)

     names  age  score  branch Example result
0    bunny   20     65   False       a   fail
1   rohith   21     76   False       b   fail
2     gani   22     97    True       c   pass
3    sallu   44     83   False       d   fail
4  bharath   43     93    True       e   pass

In [ ]:
df.rename(columns={'names':'student','score':'marks'},inplace=True)

In [ ]:
print(df)

   student  age  marks  branch Example result
0    bunny   20     65   False       a   fail
1   rohith   21     76   False       b   fail
2     gani   22     97    True       c   pass
3    sallu   44     83   False       d   fail
4  bharath   43     93    True       e   pass

In [ ]:
df.dropna()

   student  age  marks  branch Example result
0    bunny   20     65   False       a   fail
1   rohith   21     76   False       b   fail
2     gani   22     97    True       c   pass
3    sallu   44     83   False       d   fail
4  bharath   43     93    True       e   pass

In [ ]:
df.dropna(axis=1)

   student  age  marks  branch Example result
0    bunny   20     65   False       a   fail
1   rohith   21     76   False       b   fail
2     gani   22     97    True       c   pass
3    sallu   44     83   False       d   fail
4  bharath   43     93    True       e   pass

In [ ]:
df.dropna(thresh=2)

   student  age  marks  branch Example result
0    bunny   20     65   False       a   fail
1   rohith   21     76   False       b   fail
2     gani   22     97    True       c   pass
3    sallu   44     83   False       d   fail
4  bharath   43     93    True       e   pass

In [474]:
df.replace('a',np.nan,inplace=True)
print(df)

   student  age  marks  branch Example result
0    bunny   20     65   False     NaN   fail
1   rohith   21     76   False       b   fail
2     gani   22     97    True       c   pass
3    sallu   44     83   False       d   fail
4  bharath   43     93    True       e   pass

In [475]:
df.sort_values('marks',ascending=True)
print(df)

   student  age  marks  branch Example result
0    bunny   20     65   False     NaN   fail
1   rohith   21     76   False       b   fail
2     gani   22     97    True       c   pass
3    sallu   44     83   False       d   fail
4  bharath   43     93    True       e   pass

In [486]:
df.sort_values(['age','marks'],ascending=[True, False])
print(df)

   student  age  marks  branch Example result
0    bunny   20     65   False     NaN   fail
1   rohith   21     76   False       b   fail
2     gani   22     97    True       c   pass
3    sallu   44     83   False       d   fail
4  bharath   43     93    True       e   pass

In [490]:
df.nlargest(2,"marks")
df.nsmallest(3,"age")

  student  age  marks  branch Example result
0   bunny   20     65   False     NaN   fail
1  rohith   21     76   False       b   fail
2    gani   22     97    True       c   pass

In [491]:
employees = pd.DataFrame({
    'emp_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'dept_id': [10, 20, 10, 30]
})

departments = pd.DataFrame({
    'dept_id': [10, 20],
    'dept_name': ['Engineering', 'HR']
})

In [492]:
pd.merge(employees,departments,on='dept_id')

   emp_id     name  dept_id    dept_name
0       1    Alice       10  Engineering
1       2      Bob       20           HR
2       3  Charlie       10  Engineering