## **`PANDAS`**

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

2.2.2

# series :-A Series is like a single column in Excel or a list with labels (indexes).

In [4]:
s=pd.Series([1,2,3,4,5])

In [5]:
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
ser=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(ser)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [23]:
student={
    "name":"vamsi",
    "branch":"aiml"
    }
ser=pd.Series(student)
print(ser)

name      vamsi
branch     aiml
dtype: object

In [32]:
n=pd.Series([10,20,30,40,50])

In [25]:
n+2

0    12
1    22
2    32
3    42
4    52
dtype: int64

In [28]:
n/2

0     5.0
1    10.0
2    15.0
3    20.0
4    25.0
dtype: float64

In [40]:
s.mean()

np.float64(3.0)

In [41]:
s.max()

5

In [42]:
s.sum()

np.int64(15)

In [43]:
s.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [46]:
n[n>20]

2    30
3    40
4    50
dtype: int64

In [53]:
names=pd.Series(['bunny','Rohith','YUNUS'])

In [54]:
names.str.lower()

0     bunny
1    rohith
2     yunus
dtype: object

In [55]:
names.str.len()

0    5
1    6
2    5
dtype: int64

In [57]:
names.str.startswith('Y')

0    False
1    False
2     True
dtype: bool

In [62]:
student={
    "names":["bunny","rohith","gani"],
    "branch":["aiml","aiml","aiml"]
}
std=[
    {"name":"bunny","branch":"aiml","age":20,},
    {"name":"rohith","branch":"aiml"},
    {"name":"gani","branch":"aiml"}
]
s=pd.DataFrame(std)
print(s)

     name branch   age
0   bunny   aiml  20.0
1  rohith   aiml   NaN
2    gani   aiml   NaN

In [66]:
import numpy as np

In [67]:
arr= np.random.rand(3,4)
c=pd.DataFrame(arr,columns=['a','b','c','d'])
print(c)

          a         b         c         d
0  0.736824  0.500892  0.481459  0.385028
1  0.948852  0.321876  0.192430  0.387504
2  0.091132  0.410583  0.938805  0.400915

In [114]:
data={
    "names":["bunny","bunny","gani"],
    "age":[20,21,22],
    "score": [90,91,92],
    "branch":["aiml","aiml","aiml"]
}
df=pd.DataFrame(data)
print(df)

   names  age  score branch
0  bunny   20     90   aiml
1  bunny   21     91   aiml
2   gani   22     92   aiml

In [115]:
df.tail()

   names  age  score branch
0  bunny   20     90   aiml
1  bunny   21     91   aiml
2   gani   22     92   aiml

In [116]:
df.head()

   names  age  score branch
0  bunny   20     90   aiml
1  bunny   21     91   aiml
2   gani   22     92   aiml

In [86]:
df.shape()

TypeError: 'tuple' object is not callable

In [87]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [88]:
df.dtypes

names     object
age        int64
score      int64
branch    object
dtype: object

In [92]:
df.nunique()

names     2
age       3
score     3
branch    1
dtype: int64

In [90]:
df.isnull().sum()

names     0
age       0
score     0
branch    0
dtype: int64

In [99]:
df['names']
df.names

0    bunny
1    bunny
2     gani
Name: names, dtype: object

In [101]:
df[['names','age']]

   names  age
0  bunny   20
1  bunny   21
2   gani   22

In [103]:
df.loc[0]

names     bunny
age          20
score        90
branch     aiml
Name: 0, dtype: object

In [126]:
df.loc[0:3,"names":"score"]

   names  age  score
0  bunny   20     90
1  bunny   21     91
2   gani   22     92

In [127]:
df.iloc[-1]

names     gani
age         22
score       92
branch    aiml
Name: 2, dtype: object

In [130]:
df.loc[0,'names']

'bunny'

In [132]:
df.iloc[0,0]

'bunny'